name: backstage-test
'on':
  workflow_dispatch:
    inputs:
      instance_name:
        description: Name of the AWS Instance
        required: false
      aws_region:
        description: AWS Region for the instance
        required: false
      instance_type:
        description: AWS instance type
        required: false
      action:
        description: Action to perform (apply/destroy)
        required: true
jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    if: '${{ github.event.inputs.action == ''apply'' }}'
    steps:
      - name: Apply terraform
        run: echo "apply complete"
  terraform-destroy:
    runs-on: ubuntu-latest
    if: '${{github.event.inputs.action == ''destroy''))'
    steps:
      - name: Destroy the environment
        run: echo "destroy complete"
