name: Terraform CI
on:
  workflow_dispatch:
    inputs:
      instance_name:
        description: 'Name of the AWS Instance'  
        required: true 
      aws_region:
        description: 'AWS Region for the instance'
        required: true
      instance_type:
        description: 'AWS instance type'
        required: true
      action:
        description: 'Action to perform (apply/destroy)'
        required: true

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    
  
    if: ${{ github.event.inputs.action == 'apply' }}
    steps:
    
    - name: Checkout code
      run: echo "apply complete"
      
  terraform-destroy:
    runs-on: ubuntu-latest

    if: ${{github.event.inputs.action == 'destroy'))
    steps:

    - name: Destroy the environment
      run: echo "destroy complete"
